tags:
  owner: "DevOps Team"
  team: "Platform Engineering"
  environment: "dev"
  project: "titanic-api"
  created_by: "Terraform"
  cloud_provider: "aws"
  confidentiality: "internal"
  costcenter: "dev-titanic-eng"

region:
  primary: "us-east-1"
  secondary: "us-west-2"

vpc:
  cidr: "10.0.0.0/16"
  azs: ["us-east-1a", "us-east-1b"]
  private_subnets: ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets: ["10.0.101.0/24", "10.0.102.0/24"]
  enable_nat_gateway: true
  single_nat_gateway: true

eks:
  cluster_version: "1.29"
  node_instance_types: ["t3.medium"]
  node_desired_size: 2
  node_min_size: 1
  node_max_size: 3
  node_disk_size: 20

rds:
  engine: "postgres"
  engine_version: "15.4"
  instance_class: "db.t3.micro"
  allocated_storage: 20
  max_allocated_storage: 100
  db_name: "titanic_db"
  db_username: "titanic"
  multi_az: false
  backup_retention_period: 7
  deletion_protection: false
